

import { StatKey, Language, DamageType } from './types';

export const BASE_STATS_KEYS: StatKey[] = [
  "number_of_cannons",
  "damage",
  "fire_rate",
  "range",
  "crit_chance",
  "crit_power",
  "overheat",
  "cooldown"
];

// Replaced 'elem_damage' with specific damage types
export const CHIP_STATS_KEYS: StatKey[] = [
  "level",
  "damage",
  "dmg_em",
  "dmg_thermal",
  "dmg_kinetic",
  "dmg_destroyers",
  "dmg_aliens",
  "dmg_elidium",
  "dmg_total",
  "fire_rate",
  "range",
  "crit_chance",
  "crit_power",
  "overheat",
  "cooldown"
];

export const LABELS: Record<Language, Record<StatKey, string>> = {
  en: {
    number_of_cannons: "Number of Cannons",
    damage: "Damage",
    fire_rate: "Fire Rate",
    range: "Range",
    crit_chance: "Crit Chance",
    crit_power: "Crit Power",
    overheat: "Overheat",
    cooldown: "Cooldown",
    elem_damage: "Elem. Damage",
    dmg_em: "EM Damage",
    dmg_thermal: "Therm. Damage",
    dmg_kinetic: "Kinetic Damage",
    dmg_destroyers: "Dmg vs Destroyers",
    dmg_aliens: "Dmg vs Aliens",
    dmg_elidium: "Dmg vs Elidium",
    dmg_total: "Total Damage",
    level: "Chip Level"
  },
  ru: {
    number_of_cannons: "Количество орудий",
    damage: "Урон",
    fire_rate: "Скоростр.",
    range: "Дальность",
    crit_chance: "Шанс крита",
    crit_power: "Сила крита",
    overheat: "Перегрев",
    cooldown: "Остывание",
    elem_damage: "Элем. урон",
    dmg_em: "ЭМ урон",
    dmg_thermal: "Терм. урон",
    dmg_kinetic: "Кинет. урон",
    dmg_destroyers: "Урон эсминцам",
    dmg_aliens: "Урон пришельцам",
    dmg_elidium: "Урон Элидиуму",
    dmg_total: "Общий урон",
    level: "Уровень чипа"
  }
};

export const BASE_TOOLTIPS: Record<Language, Record<StatKey, string>> = {
  en: {
    number_of_cannons: "Number of cannons equipped on the ship.",
    damage: "Base weapon damage per shot before modifiers.",
    fire_rate: "Base rate of fire in rounds per minute (RPM).",
    range: "Base maximum effective firing range in meters.",
    crit_chance: "Base probability (%) of landing a critical hit.",
    crit_power: "Base damage multiplier applied during a critical hit.",
    overheat: "Continuous firing time (seconds) before weapon overheats.",
    cooldown: "Time (seconds) required for the weapon to cool down completely.",
    elem_damage: "",
    dmg_em: "",
    dmg_thermal: "",
    dmg_kinetic: "",
    dmg_destroyers: "",
    dmg_aliens: "",
    dmg_elidium: "",
    dmg_total: "",
    level: ""
  },
  ru: {
    number_of_cannons: "Количество орудий, установленных на корабле.",
    damage: "Базовый урон орудия за один выстрел.",
    fire_rate: "Базовая скорострельность (выстрелов в минуту).",
    range: "Базовая максимальная дальность стрельбы (метры).",
    crit_chance: "Базовая вероятность (%) нанесения критического урона.",
    crit_power: "Базовый множитель урона при критическом попадании.",
    overheat: "Время непрерывной стрельбы до перегрева (сек).",
    cooldown: "Время полного остывания оружия после перегрева (сек).",
    elem_damage: "",
    dmg_em: "",
    dmg_thermal: "",
    dmg_kinetic: "",
    dmg_destroyers: "",
    dmg_aliens: "",
    dmg_elidium: "",
    dmg_total: "",
    level: ""
  }
};

export const CHIP_TOOLTIPS: Record<Language, Record<StatKey, string>> = {
  en: {
    number_of_cannons: "",
    damage: "Percentage damage modifier.",
    fire_rate: "Percentage fire rate modifier.",
    range: "Percentage range modifier.",
    crit_chance: "Percentage critical chance modifier (additive).",
    crit_power: "Percentage critical power modifier (additive).",
    overheat: "Percentage modifier to weapon overheat time. Positive increases duration.",
    cooldown: "Percentage modifier to weapon cooldown time. Negative reduces wait.",
    elem_damage: "Bonus damage (%) of the weapon's elemental type.",
    dmg_em: "Bonus damage (%) specifically for Electromagnetic weapons.",
    dmg_thermal: "Bonus damage (%) specifically for Thermal weapons.",
    dmg_kinetic: "Bonus damage (%) specifically for Kinetic weapons.",
    dmg_destroyers: "Percentage damage bonus against Destroyer class ships.",
    dmg_aliens: "Percentage damage bonus against Alien faction ships.",
    dmg_elidium: "Percentage damage bonus against Elidium faction ships/structures.",
    dmg_total: "Normal mode: additive bonus to base damage. Beta mode: multiplier applied to final shot damage after all calculations.",
    level: "The rank/level of the chip (1-17)."
  },
  ru: {
    number_of_cannons: "",
    damage: "Модификатор урона (%).",
    fire_rate: "Модификатор скорострельности (%).",
    range: "Модификатор дальности (%).",
    crit_chance: "Модификатор шанса крита (%).",
    crit_power: "Модификатор силы крита (%).",
    overheat: "Модификатор времени перегрева (%). Положительное значение увеличивает время.",
    cooldown: "Модификатор времени остывания (%). Отрицательное значение уменьшает время.",
    elem_damage: "Бонус к урону (%) соответствующего типа.",
    dmg_em: "Бонус к урону (%) только для электромагнитных орудий.",
    dmg_thermal: "Бонус к урону (%) только для термических орудий.",
    dmg_kinetic: "Бонус к урону (%) только для кинетических орудий.",
    dmg_destroyers: "Бонус к урону (%) по кораблям класса Эсминец.",
    dmg_aliens: "Бонус к урону (%) по кораблям фракции Чужих.",
    dmg_elidium: "Бонус к урону (%) по кораблям фракции Элидиум.",
    dmg_total: "Обычный режим: суммируется с базовым уроном. Бета-режим: мультипликатор, применяемый к итоговому урону за выстрел после всех вычислений.",
    level: "Уровень чипа (1-17)."
  }
};

export const DAMAGE_TYPE_TOOLTIPS: Record<Language, Record<DamageType, string>> = {
  en: {
    em: "Electromagnetic",
    thermal: "Thermal",
    kinetic: "Kinetic"
  },
  ru: {
    em: "Электромагнитный",
    thermal: "Термический",
    kinetic: "Кинетический"
  }
};

export const UI_TEXT = {
  en: {
    appTitle: "Star Conflict chip damage calc",
    currentConfig: "Current Config",
    savedConfigs: "Saved Configurations",
    noSavedConfigs: "No saved configs.",
    baseStats: "Base Weapon Statistics (from Atlas)",
    chipsConfig: "Chips Configuration",
    modules: "Modules",
    chip: "Chip",
    specOps: "Special Ops",
    general: "General",
    finalAttributes: "Final Attributes",
    analysis: "Analysis",
    candidateStats: "Candidate Chip Stats",
    recommendations: "Recommendations",
    enterCandidate: "Enter candidate stats to see replacement suggestions.",
    replaceChip: "Replace Chip",
    apply: "Apply",
    reset: "Reset",
    dpm: "DPM",
    totalDps: "Total DPS",
    cleanDps: "Clean DPS",
    critDps: "Crit DPS",
    saveAlert: "Configuration saved!",
    deleteConfirm: "Delete config",
    configNamePlaceholder: "Config Name",
    emptyRecs: "Enter candidate stats to see replacement suggestions.",
    gain: "Gain",
    loss: "Loss",
    damageType: "Damage Type",
    legacyWarning: "Converted from legacy 'Elemental Damage'. Please verify.",
    ammo: "Ammo",
    shipModifiers: "Ship Modifiers",
    configLoaded: "Configuration loaded",
    candidatePreserved: "",
    configDeleted: "Configuration deleted",
    newConfig: "New Ship",
    newConfigCreated: "New empty configuration created",
    exportBackup: "Export Backup",
    configExported: "Configuration exported",
    importBackup: "Import Backup",
    importSuccess: "Configurations imported",
    importError: "Invalid backup file",
    noAmmo: "No compatible ammo for selected damage type.",
    noModules: "No compatible modules for selected damage type.",
    implants: "Implants",
    noImplants: "No compatible implants for selected damage type.",
    rank: "Rank",
    count: "Count",
    betaVersion: "Beta Version",
    betaPopupTitle: "Enable Beta Features?",
    betaPopupDesc: "Enabling beta version will activate experimental features. These features might change or be removed in the future. Current beta features:",
    betaPopupFeature1: "- Total Damage chip parameter acts as a final multiplier applied after all damage calculations",
    ok: "OK",
    no: "No",
    shipRank: "Ship Rank",
    chipRank: "Chip Rank",
    temporaryBuild: "Temporary Build",
    globalAnalysis: "Global Analysis",
    inventory: "Inventory",
    rankTooHigh: "Rank too high",
    improvesBy: "Improves by",
    noImprovement: "No improvement",
    saveToInventory: "Save to Inventory",
    shipEditor: "Ship Editor",
    chipInventory: "Chip Inventory",
    replacesSlot: "Replaces slot",
    dpmDelta: "DPM Delta",
    autoBuilder: "Auto-Builder",
    useOnlyAvailable: "Use only available chips (not used in other builds)",
    optimizeFor: "Optimize for:",
    foundChips: "Found",
    matchingCriteria: "chips matching criteria",
    cancel: "Cancel",
    build: "Build",
    autoBuildApplied: "Auto-Build Applied",
    chipsUpdated: "Chips have been updated.",
    noChipsSaved: "No chips saved yet.",
    saveChipsHint: "Save chips from the Analysis panel to build your inventory.",
    previewChanges: "Preview Changes",
    scanMissing: "Scan Builds",
    scanComplete: "Added {count} missing chips to inventory",
    noMissingChipsFound: "No missing chips found",
    duplicateChip: "Duplicate chip ignored",
    loadAsCandidate: "Load as Candidate",
    loadAsCandidateHint: "Double-click to load as candidate",
    loadConfigTooltip: "Double-click to load ship configuration",
    forceCrit: "Hull < 15%",
    forceCritTooltip: "Hull integrity below 15% — guarantees 100% crit chance",
    changeChip: "Change Chip",
    createNewChip: "Create New Chip",
    chipLinkedBanner: "Editing stats updates this chip in your inventory. Use \"Change Chip\" to swap to a different chip.",
    chipUnlinked: "Not linked to inventory",
    selectInventoryChip: "Select from Inventory",
    chipSwitcherTitle: "Change Chip in Slot",
    linkToInventory: "Link to Inventory",
    chipsInInventory: "chips in inventory",
    noChipsInInventory: "No chips in inventory yet. Create one below.",
    configSyncedChips: "chips were added to inventory from this config",
    minRange: "Min. Range (m)",
    minRangeHint: "Minimum acceptable range in meters (0 = disabled). If the result is higher — that's fine.",
    minOverheat: "Min. Overheat (sec)",
    minOverheatHint: "Minimum acceptable overheat time in seconds (0 = disabled). If the result is higher — that's fine.",
    constraintViolatedRange: "Build violates range constraint (range too low)",
    constraintViolatedOverheat: "Build violates overheat constraint (overheat too low)",
    constraintViolatedNotApplicable: "No valid build found satisfying constraints — constraints will be ignored.",
    slotUnchanged: "Unchanged",
    slotChanged: "Changed",
    chipSlots: "Chip Slots"
  },
  ru: {
    appTitle: "Калькулятор урона чипов Star Conflict",
    currentConfig: "Текущая конфигурация",
    savedConfigs: "Сохраненные",
    noSavedConfigs: "Нет сохраненных.",
    baseStats: "Базовые параметры оружия (из Атласа)",
    chipsConfig: "Настройка чипов",
    modules: "Модули",
    chip: "Чип",
    specOps: "Спецоперация",
    general: "Обычный режим",
    finalAttributes: "Итоговые параметры",
    analysis: "Сравнение",
    candidateStats: "Параметры чипа-кандидата",
    recommendations: "Рекомендации",
    enterCandidate: "Введите параметры чипа для получения предложений по замене.",
    replaceChip: "Заменить чип",
    apply: "Применить",
    reset: "Сброс",
    dpm: "DPM",
    totalDps: "DPS",
    cleanDps: "Чистый DPS",
    critDps: "Крит DPS",
    saveAlert: "Конфигурация сохранена!",
    deleteConfirm: "Удалить конфиг",
    configNamePlaceholder: "Название конфига",
    emptyRecs: "Введите характеристики нового чипа для сравнения.",
    gain: "Прирост",
    loss: "Штраф",
    damageType: "Тип урона",
    legacyWarning: "Конвертировано из устаревшего 'Элем. урона'. Проверьте.",
    ammo: "Боеприпасы",
    shipModifiers: "Модификаторы корабля",
    configLoaded: "Конфигурация загружена",
    candidatePreserved: "",
    configDeleted: "Конфигурация удалена",
    newConfig: "Новый корабль",
    newConfigCreated: "Создана новая пустая конфигурация",
    exportBackup: "Экспорт бэкапа",
    configExported: "Конфигурация экспортирована",
    importBackup: "Импорт бэкапа",
    importSuccess: "Конфигурации импортированы",
    importError: "Неверный файл бэкапа",
    noAmmo: "Нет совместимых боеприпасов для выбранного типа урона.",
    noModules: "Нет совместимых модулей для выбранного типа урона.",
    implants: "Импланты",
    noImplants: "Нет совместимых имплантов для выбранного типа урона.",
    rank: "Ранг",
    count: "Количество",
    betaVersion: "Бета-версия",
    betaPopupTitle: "Включить бета-функции?",
    betaPopupDesc: "Включение бета-версии активирует экспериментальные функции. Эти функции могут измениться или быть удалены в будущем. Текущие бета-функции:",
    betaPopupFeature1: "- Параметр чипа Общий урон является итоговым мультипликатором, применяемым после всех вычислений урона",
    ok: "ОК",
    no: "Нет",
    shipRank: "Ранг корабля",
    chipRank: "Ранг чипа",
    temporaryBuild: "Временная сборка",
    globalAnalysis: "Глобальный анализ",
    inventory: "Инвентарь",
    rankTooHigh: "Ранг слишком высок",
    improvesBy: "Улучшает на",
    noImprovement: "Нет улучшений",
    saveToInventory: "Сохранить в инвентарь",
    shipEditor: "Редактор корабля",
    chipInventory: "Инвентарь чипов",
    replacesSlot: "Заменяет слот",
    dpmDelta: "Изменение DPM",
    autoBuilder: "Авто-сборка",
    useOnlyAvailable: "Использовать только доступные чипы (не занятые в других сборках)",
    optimizeFor: "Оптимизировать для:",
    foundChips: "Найдено",
    matchingCriteria: "чипов, подходящих под критерии",
    cancel: "Отмена",
    build: "Собрать",
    autoBuildApplied: "Авто-сборка применена",
    chipsUpdated: "Чипы были обновлены.",
    noChipsSaved: "Пока нет сохраненных чипов.",
    saveChipsHint: "Сохраняйте чипы из панели сравнения, чтобы собрать инвентарь.",
    previewChanges: "Предварительный просмотр",
    scanMissing: "Сканировать сборки",
    scanComplete: "Добавлено {count} пропущенных чипов в инвентарь",
    noMissingChipsFound: "Пропущенных чипов не найдено",
    duplicateChip: "Дубликат чипа проигнорирован",
    loadAsCandidate: "Загрузить как кандидат",
    loadAsCandidateHint: "Двойной клик — загрузить как кандидат",
    loadConfigTooltip: "Двойной клик — загрузить конфигурацию корабля",
    forceCrit: "Прочн. < 15%",
    forceCritTooltip: "Прочность корпуса менее 15% — обеспечивает 100% шанс крита",
    changeChip: "Сменить чип",
    createNewChip: "Создать новый чип",
    chipLinkedBanner: "Редактирование параметров обновляет этот чип в инвентаре. Для смены чипа используйте кнопку \"Сменить чип\".",
    chipUnlinked: "Не привязан к инвентарю",
    selectInventoryChip: "Выбрать из инвентаря",
    chipSwitcherTitle: "Сменить чип в слоте",
    linkToInventory: "Привязать к инвентарю",
    chipsInInventory: "чипов в инвентаре",
    noChipsInInventory: "В инвентаре пока нет чипов. Создайте ниже.",
    configSyncedChips: "чипов добавлено в инвентарь из этой конфигурации",
    minRange: "Мин. дальность (м)",
    minRangeHint: "Минимально допустимая дальность в метрах (0 = отключено). Если результат больше — всё хорошо.",
    minOverheat: "Мин. перегрев (сек)",
    minOverheatHint: "Минимально допустимое время перегрева в секундах (0 = отключено). Если результат больше — всё хорошо.",
    constraintViolatedRange: "Сборка нарушает ограничение дальности (дальность слишком маленькая)",
    constraintViolatedOverheat: "Сборка нарушает ограничение перегрева (перегрев слишком маленький)",
    constraintViolatedNotApplicable: "Не найдено подходящей сборки — ограничения игнорируются.",
    slotUnchanged: "Остался прежним",
    slotChanged: "Изменился",
    chipSlots: "Слоты чипов"
  }
};

export const DEFAULT_BASE_STATS: Record<StatKey, number> = {
  number_of_cannons: 1,
  damage: 0,
  fire_rate: 0,
  range: 0,
  crit_chance: 0,
  crit_power: 0,
  overheat: 0,
  cooldown: 0,
  elem_damage: 0,
  dmg_em: 0,
  dmg_thermal: 0,
  dmg_kinetic: 0,
  dmg_destroyers: 0,
  dmg_aliens: 0,
  dmg_elidium: 0,
  dmg_total: 0,
  level: 15
};

export const DEFAULT_CHIP_STATS: Record<StatKey, number> = {
  ...DEFAULT_BASE_STATS
};